import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./typography.css";
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";
import AnimationController from "./waltDisney/AnimationController";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="body">
        <AnimationController env={process.env.MEDIA_LIBRARY}>
          <Navbar />
          {children}
        </AnimationController>
      </body>
    </html>
  );
}
